version: '3'
services:
  app:
    image: miztch/file-uploader:latest
    environment:
      - AWS_REGION=us-east-1
      - S3_BUCKET=<YOUR AMAZON S3 BUCKET>
      - DYNAMODB_TABLE=<YOUR AMAZON DYNAMODB TABLE>
    volumes:
      - socket:/tmp
    command: uwsgi --ini /app/app.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - socket:/tmp

volumes:
  socket: